### ISSUE TITLE
exe

### ISSUE THREAD

**Issue by hitparslan** [ShadowNate/MISETranslator#12]
Hello,
It can be a stupid question but I couldn't find the exe. I'm not the programmer. I want to translate Monkey Island SE to turkish but couldn't find the exe.

**Comment by martanius** [comment]
I have the same issue. Did you solve this?

**Comment by antoniou79** [comment]
> I have the same issue. Did you solve this?

It seems that a while ago, Google updated their security policies and the exe file was removed due to those new policies. 
While I understand the inconvenience, I think it's for the best. Most new Operating Systems and system security apps won't "like" a new executable from an unknown publisher/party and will probably flag it as potentially harmful.

I would suggest setting up the Python 2.7 environment and running the editor that way as a set of python scripts. 

Again, sorry for the inconvenience. It's also been a while since I've updated the code. I wanted to migrate to the newer Python 3.x  and Qt 5 or higher, but I never got the time to do this. Hopefully it still runs without issues with the old Python, libs and Qt.  We used it successfully for the full translation of SoMI: SE and the ongoing-but-mostly-done translation of MI2:SE to Greek.

**Comment by martanius** [comment]
Thank you for your reply.

Could you re-upload the exe file, if you have it backed up?

Or make some tutorial on how to set up the python environment and run set of scripts from there? When I run the .py scripts in folder, my cmd line app just pops up and closes again.

**Comment by antoniou79** [comment]
The instructions for running with Python (iirc I was running from command line, so that I could look at any warnings, info, debug messages at the console output) are in the readme of the source code --also shown at the project's source code view on github.
The info is in the section called "Modifying the source code and running with Python 2.7"
I seem to have a backup of version 4.9.7 (which is the same as 4.97 because I didn't pay much attention to being consistent with the labels) here:
https://drive.google.com/file/d/0B8pmRRU8RZN7RVFjZklOdm4zcU0/view?usp=sharing&resourcekey=0-kdvRGkG_kJ9zglHHVeCraQ
Latest version of the code is 4.9.9 (aka 4.99) with minor fixes. If you need those (see changelog in source code), you'll have to run from the sources using Python. If not, try the above exe.

**Comment by martanius** [comment]
Thank you. This helped a lot :)

All I need to do is edit the font for my language. The game is Monkey Island 2:SE.
I was just testing it around and for me it won't detect any characters. I didn't create my new PNG yet, but I thought after pressing Calculate it will pull the coordinates and definitions from the FONT file so I could import my coordinates and save it in the FONT file.
https://prnt.sc/25vysix

Well, I'll play around with it and hopefully I'll get a hang of it. Thank you for sharing the older version :)

**EDIT**
Yep, figured it out. Now it should work as I hope it will. Thank you so much for creating this tool (or participating in the creation)!!
